markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Albert Gonzalez
url: http://siemplicity.github.io
description: SIEMplify thru detection, correlation and data visualization.
twitter: albgnz
